[package]
name = "bluebrick"
version = "0.1.0"
edition = "2024"

[dependencies]
ctor = "0.4.1"
dlopen = "0.1.8"
msgbox = "0.7.0"
retour = { version = "0.3.1", features = ["static-detour", "thiscall-abi"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.60.0", features = ["Win32_System_LibraryLoader"] }

[lib]
crate-type = [ "cdylib", "lib" ]
