use colored::Color;

pub enum WebColor {
    AliceBlue,
    AntiqueWhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    Black,
    BlanchedAlmond,
    Blue,
    BlueViolet,
    Brown,
    BurlyWood,
    CadetBlue,
    Chartreuse,
    Chocolate,
    Coral,
    CornflowerBlue,
    Cornsilk,
    Crimson,
    Cyan,
    DarkBlue,
    DarkCyan,
    DarkGoldenrod,
    DarkGray,
    DarkGreen,
    DarkKhaki,
    DarkMagenta,
    DarkOliveGreen,
    DarkOrange,
    DarkOrchid,
    DarkRed,
    DarkSalmon,
    DarkSeaGreen,
    DarkSlateBlue,
    DarkSlateGray,
    DarkTurquoise,
    DarkViolet,
    DeepPink,
    DeepSkyBlue,
    DimGray,
    DodgerBlue,
    Firebrick,
    FloralWhite,
    ForestGreen,
    Fuchsia,
    Gainsboro,
    GhostWhite,
    Gold,
    Goldenrod,
    Gray,
    Green,
    GreenYellow,
    Honeydew,
    HotPink,
    IndianRed,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    LavenderBlush,
    LawnGreen,
    LemonChiffon,
    LightBlue,
    LightCoral,
    LightCyan,
    LightGoldenrodYellow,
    LightGray,
    LightGreen,
    LightPink,
    LightSalmon,
    LightSeaGreen,
    LightSkyBlue,
    LightSlateGray,
    LightSteelBlue,
    LightYellow,
    Lime,
    LimeGreen,
    Linen,
    Magenta,
    Maroon,
    MediumAquamarine,
    MediumBlue,
    MediumOrchid,
    MediumPurple,
    MediumSeaGreen,
    MediumSlateBlue,
    MediumSpringGreen,
    MediumTurquoise,
    MediumVioletRed,
    MidnightBlue,
    MintCream,
    MistyRose,
    Moccasin,
    NavajoWhite,
    Navy,
    OldLace,
    Olive,
    OliveDrab,
    Orange,
    OrangeRed,
    Orchid,
    PaleGoldenrod,
    PaleGreen,
    PaleTurquoise,
    PaleVioletRed,
    PapayaWhip,
    PeachPuff,
    Peru,
    Pink,
    Plum,
    PowderBlue,
    Purple,
    RebeccaPurple,
    Red,
    RosyBrown,
    RoyalBlue,
    SaddleBrown,
    Salmon,
    SandyBrown,
    SeaGreen,
    SeaShell,
    Sienna,
    Silver,
    SkyBlue,
    SlateBlue,
    SlateGray,
    Snow,
    SpringGreen,
    SteelBlue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Turquoise,
    Violet,
    Wheat,
    White,
    WhiteSmoke,
    Yellow,
    YellowGreen,
}

impl Into<Color> for WebColor {
    fn into(self) -> Color {
        use WebColor::*;
        match self {
            AliceBlue => Color::TrueColor { r: 0xF0, g: 0xF8, b: 0xFF },
            AntiqueWhite => Color::TrueColor { r: 0xFA, g: 0xEB, b: 0xD7 },
            Aqua => Color::TrueColor { r: 0x00, g: 0xFF, b: 0xFF },
            Aquamarine => Color::TrueColor { r: 0x7F, g: 0xFF, b: 0xD4 },
            Azure => Color::TrueColor { r: 0xF0, g: 0xFF, b: 0xFF },
            Beige => Color::TrueColor { r: 0xF5, g: 0xF5, b: 0xDC },
            Bisque => Color::TrueColor { r: 0xFF, g: 0xE4, b: 0xC4 },
            Black => Color::TrueColor { r: 0x00, g: 0x00, b: 0x00 },
            BlanchedAlmond => Color::TrueColor { r: 0xFF, g: 0xEB, b: 0xCD },
            Blue => Color::TrueColor { r: 0x00, g: 0x00, b: 0xFF },
            BlueViolet => Color::TrueColor { r: 0x8A, g: 0x2B, b: 0xE2 },
            Brown => Color::TrueColor { r: 0xA5, g: 0x2A, b: 0x2A },
            BurlyWood => Color::TrueColor { r: 0xDE, g: 0xB8, b: 0x87 },
            CadetBlue => Color::TrueColor { r: 0x5F, g: 0x9E, b: 0xA0 },
            Chartreuse => Color::TrueColor { r: 0x7F, g: 0xFF, b: 0x00 },
            Chocolate => Color::TrueColor { r: 0xD2, g: 0x69, b: 0x1E },
            Coral => Color::TrueColor { r: 0xFF, g: 0x7F, b: 0x50 },
            CornflowerBlue => Color::TrueColor { r: 0x64, g: 0x95, b: 0xED },
            Cornsilk => Color::TrueColor { r: 0xFF, g: 0xF8, b: 0xDC },
            Crimson => Color::TrueColor { r: 0xDC, g: 0x14, b: 0x3C },
            Cyan => Color::TrueColor { r: 0x00, g: 0xFF, b: 0xFF },
            DarkBlue => Color::TrueColor { r: 0x00, g: 0x00, b: 0x8B },
            DarkCyan => Color::TrueColor { r: 0x00, g: 0x8B, b: 0x8B },
            DarkGoldenrod => Color::TrueColor { r: 0xB8, g: 0x86, b: 0x0B },
            DarkGray => Color::TrueColor { r: 0xA9, g: 0xA9, b: 0xA9 },
            DarkGreen => Color::TrueColor { r: 0x00, g: 0x64, b: 0x00 },
            DarkKhaki => Color::TrueColor { r: 0xBD, g: 0xB7, b: 0x6B },
            DarkMagenta => Color::TrueColor { r: 0x8B, g: 0x00, b: 0x8B },
            DarkOliveGreen => Color::TrueColor { r: 0x55, g: 0x6B, b: 0x2F },
            DarkOrange => Color::TrueColor { r: 0xFF, g: 0x8C, b: 0x00 },
            DarkOrchid => Color::TrueColor { r: 0x99, g: 0x32, b: 0xCC },
            DarkRed => Color::TrueColor { r: 0x8B, g: 0x00, b: 0x00 },
            DarkSalmon => Color::TrueColor { r: 0xE9, g: 0x96, b: 0x7A },
            DarkSeaGreen => Color::TrueColor { r: 0x8F, g: 0xBC, b: 0x8B },
            DarkSlateBlue => Color::TrueColor { r: 0x48, g: 0x3D, b: 0x8B },
            DarkSlateGray => Color::TrueColor { r: 0x2F, g: 0x4F, b: 0x4F },
            DarkTurquoise => Color::TrueColor { r: 0x00, g: 0xCE, b: 0xD1 },
            DarkViolet => Color::TrueColor { r: 0x94, g: 0x00, b: 0xD3 },
            DeepPink => Color::TrueColor { r: 0xFF, g: 0x14, b: 0x93 },
            DeepSkyBlue => Color::TrueColor { r: 0x00, g: 0xBF, b: 0xFF },
            DimGray => Color::TrueColor { r: 0x69, g: 0x69, b: 0x69 },
            DodgerBlue => Color::TrueColor { r: 0x1E, g: 0x90, b: 0xFF },
            Firebrick => Color::TrueColor { r: 0xB2, g: 0x22, b: 0x22 },
            FloralWhite => Color::TrueColor { r: 0xFF, g: 0xFA, b: 0xF0 },
            ForestGreen => Color::TrueColor { r: 0x22, g: 0x8B, b: 0x22 },
            Fuchsia => Color::TrueColor { r: 0xFF, g: 0x00, b: 0xFF },
            Gainsboro => Color::TrueColor { r: 0xDC, g: 0xDC, b: 0xDC },
            GhostWhite => Color::TrueColor { r: 0xF8, g: 0xF8, b: 0xFF },
            Gold => Color::TrueColor { r: 0xFF, g: 0xD7, b: 0x00 },
            Goldenrod => Color::TrueColor { r: 0xDA, g: 0xA5, b: 0x20 },
            Gray => Color::TrueColor { r: 0x80, g: 0x80, b: 0x80 },
            Green => Color::TrueColor { r: 0x00, g: 0x80, b: 0x00 },
            GreenYellow => Color::TrueColor { r: 0xAD, g: 0xFF, b: 0x2F },
            Honeydew => Color::TrueColor { r: 0xF0, g: 0xFF, b: 0xF0 },
            HotPink => Color::TrueColor { r: 0xFF, g: 0x69, b: 0xB4 },
            IndianRed => Color::TrueColor { r: 0xCD, g: 0x5C, b: 0x5C },
            Indigo => Color::TrueColor { r: 0x4B, g: 0x00, b: 0x82 },
            Ivory => Color::TrueColor { r: 0xFF, g: 0xFF, b: 0xF0 },
            Khaki => Color::TrueColor { r: 0xF0, g: 0xE6, b: 0x8C },
            Lavender => Color::TrueColor { r: 0xE6, g: 0xE6, b: 0xFA },
            LavenderBlush => Color::TrueColor { r: 0xFF, g: 0xF0, b: 0xF5 },
            LawnGreen => Color::TrueColor { r: 0x7C, g: 0xFC, b: 0x00 },
            LemonChiffon => Color::TrueColor { r: 0xFF, g: 0xFA, b: 0xCD },
            LightBlue => Color::TrueColor { r: 0xAD, g: 0xD8, b: 0xE6 },
            LightCoral => Color::TrueColor { r: 0xF0, g: 0x80, b: 0x80 },
            LightCyan => Color::TrueColor { r: 0xE0, g: 0xFF, b: 0xFF },
            LightGoldenrodYellow => Color::TrueColor { r: 0xFA, g: 0xFA, b: 0xD2 },
            LightGray => Color::TrueColor { r: 0xD3, g: 0xD3, b: 0xD3 },
            LightGreen => Color::TrueColor { r: 0x90, g: 0xEE, b: 0x90 },
            LightPink => Color::TrueColor { r: 0xFF, g: 0xB6, b: 0xC1 },
            LightSalmon => Color::TrueColor { r: 0xFF, g: 0xA0, b: 0x7A },
            LightSeaGreen => Color::TrueColor { r: 0x20, g: 0xB2, b: 0xAA },
            LightSkyBlue => Color::TrueColor { r: 0x87, g: 0xCE, b: 0xFA },
            LightSlateGray => Color::TrueColor { r: 0x77, g: 0x88, b: 0x99 },
            LightSteelBlue => Color::TrueColor { r: 0xB0, g: 0xC4, b: 0xDE },
            LightYellow => Color::TrueColor { r: 0xFF, g: 0xFF, b: 0xE0 },
            Lime => Color::TrueColor { r: 0x00, g: 0xFF, b: 0x00 },
            LimeGreen => Color::TrueColor { r: 0x32, g: 0xCD, b: 0x32 },
            Linen => Color::TrueColor { r: 0xFA, g: 0xF0, b: 0xE6 },
            Magenta => Color::TrueColor { r: 0xFF, g: 0x00, b: 0xFF },
            Maroon => Color::TrueColor { r: 0x80, g: 0x00, b: 0x00 },
            MediumAquamarine => Color::TrueColor { r: 0x66, g: 0xCD, b: 0xAA },
            MediumBlue => Color::TrueColor { r: 0x00, g: 0x00, b: 0xCD },
            MediumOrchid => Color::TrueColor { r: 0xBA, g: 0x55, b: 0xD3 },
            MediumPurple => Color::TrueColor { r: 0x93, g: 0x70, b: 0xDB },
            MediumSeaGreen => Color::TrueColor { r: 0x3C, g: 0xB3, b: 0x71 },
            MediumSlateBlue => Color::TrueColor { r: 0x7B, g: 0x68, b: 0xEE },
            MediumSpringGreen => Color::TrueColor { r: 0x00, g: 0xFA, b: 0x9A },
            MediumTurquoise => Color::TrueColor { r: 0x48, g: 0xD1, b: 0xCC },
            MediumVioletRed => Color::TrueColor { r: 0xC7, g: 0x15, b: 0x85 },
            MidnightBlue => Color::TrueColor { r: 0x19, g: 0x19, b: 0x70 },
            MintCream => Color::TrueColor { r: 0xF5, g: 0xFF, b: 0xFA },
            MistyRose => Color::TrueColor { r: 0xFF, g: 0xE4, b: 0xE1 },
            Moccasin => Color::TrueColor { r: 0xFF, g: 0xE4, b: 0xB5 },
            NavajoWhite => Color::TrueColor { r: 0xFF, g: 0xDE, b: 0xAD },
            Navy => Color::TrueColor { r: 0x00, g: 0x00, b: 0x80 },
            OldLace => Color::TrueColor { r: 0xFD, g: 0xF5, b: 0xE6 },
            Olive => Color::TrueColor { r: 0x80, g: 0x80, b: 0x00 },
            OliveDrab => Color::TrueColor { r: 0x6B, g: 0x8E, b: 0x23 },
            Orange => Color::TrueColor { r: 0xFF, g: 0xA5, b: 0x00 },
            OrangeRed => Color::TrueColor { r: 0xFF, g: 0x45, b: 0x00 },
            Orchid => Color::TrueColor { r: 0xDA, g: 0x70, b: 0xD6 },
            PaleGoldenrod => Color::TrueColor { r: 0xEE, g: 0xE8, b: 0xAA },
            PaleGreen => Color::TrueColor { r: 0x98, g: 0xFB, b: 0x98 },
            PaleTurquoise => Color::TrueColor { r: 0xAF, g: 0xEE, b: 0xEE },
            PaleVioletRed => Color::TrueColor { r: 0xDB, g: 0x70, b: 0x93 },
            PapayaWhip => Color::TrueColor { r: 0xFF, g: 0xEF, b: 0xD5 },
            PeachPuff => Color::TrueColor { r: 0xFF, g: 0xDA, b: 0xB9 },
            Peru => Color::TrueColor { r: 0xCD, g: 0x85, b: 0x3F },
            Pink => Color::TrueColor { r: 0xFF, g: 0xC0, b: 0xCB },
            Plum => Color::TrueColor { r: 0xDD, g: 0xA0, b: 0xDD },
            PowderBlue => Color::TrueColor { r: 0xB0, g: 0xE0, b: 0xE6 },
            Purple => Color::TrueColor { r: 0x80, g: 0x00, b: 0x80 },
            RebeccaPurple => Color::TrueColor { r: 0x66, g: 0x33, b: 0x99 },
            Red => Color::TrueColor { r: 0xFF, g: 0x00, b: 0x00 },
            RosyBrown => Color::TrueColor { r: 0xBC, g: 0x8F, b: 0x8F },
            RoyalBlue => Color::TrueColor { r: 0x41, g: 0x69, b: 0xE1 },
            SaddleBrown => Color::TrueColor { r: 0x8B, g: 0x45, b: 0x13 },
            Salmon => Color::TrueColor { r: 0xFA, g: 0x80, b: 0x72 },
            SandyBrown => Color::TrueColor { r: 0xF4, g: 0xA4, b: 0x60 },
            SeaGreen => Color::TrueColor { r: 0x2E, g: 0x8B, b: 0x57 },
            SeaShell => Color::TrueColor { r: 0xFF, g: 0xF5, b: 0xEE },
            Sienna => Color::TrueColor { r: 0xA0, g: 0x52, b: 0x2D },
            Silver => Color::TrueColor { r: 0xC0, g: 0xC0, b: 0xC0 },
            SkyBlue => Color::TrueColor { r: 0x87, g: 0xCE, b: 0xEB },
            SlateBlue => Color::TrueColor { r: 0x6A, g: 0x5A, b: 0xCD },
            SlateGray => Color::TrueColor { r: 0x70, g: 0x80, b: 0x90 },
            Snow => Color::TrueColor { r: 0xFF, g: 0xFA, b: 0xFA },
            SpringGreen => Color::TrueColor { r: 0x00, g: 0xFF, b: 0x7F },
            SteelBlue => Color::TrueColor { r: 0x46, g: 0x82, b: 0xB4 },
            Tan => Color::TrueColor { r: 0xD2, g: 0xB4, b: 0x8C },
            Teal => Color::TrueColor { r: 0x00, g: 0x80, b: 0x80 },
            Thistle => Color::TrueColor { r: 0xD8, g: 0xBF, b: 0xD8 },
            Tomato => Color::TrueColor { r: 0xFF, g: 0x63, b: 0x47 },
            Turquoise => Color::TrueColor { r: 0x40, g: 0xE0, b: 0xD0 },
            Violet => Color::TrueColor { r: 0xEE, g: 0x82, b: 0xEE },
            Wheat => Color::TrueColor { r: 0xF5, g: 0xDE, b: 0xB3 },
            White => Color::TrueColor { r: 0xFF, g: 0xFF, b: 0xFF },
            WhiteSmoke => Color::TrueColor { r: 0xF5, g: 0xF5, b: 0xF5 },
            Yellow => Color::TrueColor { r: 0xFF, g: 0xFF, b: 0x00 },
            YellowGreen => Color::TrueColor { r: 0x9A, g: 0xCD, b: 0x32 },
        }
    }
}
